server:
  port: 8072

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/employeedb?authSource=admin&authMechanism=SCRAM-SHA-1
    
    cassandra:
      keyspace-name: employeeks
      contact-points: 127.0.0.1
      port: 9042
      local-datacenter: datacenter1
      username: cassandra
      password: 1Password@
      schema-action: CREATE_IF_NOT_EXISTS
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
          
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: mygroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
