version: '2'
services:
  clickhouse:
    image: bitnami/clickhouse:23
    environment:
      - CLICKHOUSE_ADMIN_USER=admin
      - CLICKHOUSE_ADMIN_PASSWORD=admin
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"